version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      #- npm test
      - echo "${S3_BUCKET_NAME}"
      - echo "${S3_KEY_NAME}"
  build:
    commands:
      - zip "${S3_KEY_NAME}" index.js
      - aws s3 cp "${S3_KEY_NAME}" "s3://${S3_BUCKET_NAME}/${S3_KEY_NAME}"
  post_build:
    commands:
      - S3_VERSION=$(aws s3api get-object --bucket "${S3_BUCKET_NAME}" --key "${S3_KEY_NAME}" getobjectoutfile | jq '.VersionId')
      - echo "{\"Parameters\":{\"S3Bucket\":\"${S3_BUCKET_NAME}\",\"S3Key\":\"${S3_KEY_NAME}\",\"S3Version\":${S3_VERSION}}}" >> template-configuration.json
      - cat template-configuration.json

artifacts:
  files:
    - serverless-api.yml
    - template-configuration.json
